#!/usr/bin/env python
# USAGE:
# 	$ echo "Security Warning" | telegram-send
# 	$ cat /etc/shadow | telegram-send

# Setup:
#	Install https://github.com/luckydonald/pytgbot
#	Create new Telegarm bot via @BotFather
#	TODO: how to obtain your user id
#	$ echo 'API_KEY="<new bot's api key>"' > secret.py
#	$ echo 'USER_ID=12345' >> secret.py

from pytgbot import Bot
from secret import API_KEY, USER_ID
import sys

text = sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()

bot = Bot(API_KEY)

bot.send_message(USER_ID, text)

